import { Button, Container, Grid, Textarea } from '@nextui-org/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react';

export default function Home() {


  const inputRef = useRef(null);
  const outRef = useRef(null);

  const transfer = () => {
    let result = '';


    if (inputRef.current) {
      var input = JSON.parse(inputRef.current.value);
      const items = input.overrides;
      
      for (const item of items) {
        const name = item.model.split("/")[1];
        result += `
${name}:
  displayname: "&e${name}"
  material: NAME_TAG
  Pack:
    generate_model: true
    custom_model_data: ${item.predicate.custom_model_data}
    parent_model: "item/generated"
    textures:
      - custom/supreme-icons/${item.model}.png
          `;
      }
      outRef.current.value = result;
    }
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid.Container gap={2} justify="center" alignItems='center'>
          <Grid
            lg={6}
            direction='column'
          >
            
            <Textarea
              bordered
              color="primary"
              label="Transfer Oraxen Items"
              placeholder="Enter your json item."
              ref={inputRef}
            />
            <Container justify='center' css={{marginTop: 9, padding: 0 }}>
              <Button size="sm" onPress={transfer}>
                Transfer
              </Button>;
            </Container>

            <Textarea
              bordered
              color="success"
              label="Result"
              placeholder=""
              ref={outRef}
              row={30}
            />
          </Grid>
        
        </Grid.Container>
      </main>
    </div>
  )
}
